[package]
name = "infrastructure"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
async-trait = "0.1.68"

domain = { path = "../domain" }
# serde_json = "1.0.67"
serde = "=1.0.126"
reqwest = { version = "0.11", features = ["json"] }
# tokio = { version = "1.29.1", features = ["full"] }

