[package]
name = "infrastructure"
version = "0.0.0"
edition = "2021"


[dependencies]
anyhow = { version = "1.0" }
async-trait = "0.1.68"
domain = { path = "../domain" }
serde = "=1.0.126"
reqwest = { version = "0.11", features = ["json"] }
