version: '3'
services:
  ssr_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/usr/src/target
      - .:/usr/src/app/node_modules
      - .:/usr/src/ssr_server/node_modules

# volumesにtargetなども入れないときつそう
