[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.72"
serde = { version = "=1.0.198", default-features = false }
serde_json = { version = "1.0", default-features = false }
reqwest = { version = "0.12", default-features = false, features = [
  "rustls-tls",
  "json",
] }
async-trait = "0.1.77"
log = "0.4.20"

[profile.release]
strip = 'debuginfo'
panic = 'abort'     # 大丈夫
debug = false       # debug情報なしの設定
codegen-units = 1
opt-level = 'z'     # optレベル最高
lto = true
