[package]
name = "domain"
version = "1.1.0"
authors = ["Masahiro Okubo"]
edition = "2021"

[dependencies]
serde = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
