[package]
name = "use_case"
version = "0.2.0"
authors = ["masahiro <stmhamachiii@gmail.com>"]
edition = "2021"

[dependencies]
domain = { path = "../domain" }
infrastructure = { path = "../infrastructure" }
anyhow = { version = "1.0" }
async-trait = "0.1.68"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
