name: Deploy(common template)
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: Authenticate Google Cloud
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider
          service_account: github-action-masahiro-me@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set up gcloud authorization helper
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and push to artifact registry
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.run
          context: .
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/masahiro-me/masahiro-me:latest
