on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Format

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo clippy

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo fmt
