on:
  pull_request:
    branches:
      - main

name: Run test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo test --all-features
